//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_Creator_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginsItems
    {
        public int ID { get; set; }
        public int OriginID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Origins Origins { get; set; }
    }
}
