//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_Creator_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weapons()
        {
            this.ClassItem = new HashSet<ClassItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Damage { get; set; }
        public string Description { get; set; }
        public double Weight { get; set; }
        public Nullable<bool> TwoHanded { get; set; }
        public Nullable<bool> Long { get; set; }
        public Nullable<bool> Remote { get; set; }
        public Nullable<bool> Lung { get; set; }
        public Nullable<bool> Throwing { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<bool> Rechargeable { get; set; }
        public Nullable<bool> Heavy { get; set; }
        public Nullable<bool> Universal { get; set; }
        public Nullable<bool> Fencing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassItem> ClassItem { get; set; }
    }
}
